# 2.2 Variable变量

In [2]:
import torch
from torch.autograd import Variable

### 1. 定义Variable

In [5]:
tensor = torch.FloatTensor([[1,2],[3,4]])
v = Variable(tensor,requires_grad=True)

print(tensor)
print(v)

t_out = torch.mean(tensor*tensor)
v_out = torch.mean(v*v)

print(t_out)
print(v_out)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


### 2. 反向传递求梯度

In [6]:
v_out.backward()
print(v.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### 3.转换成numpy

In [10]:
print(v.data) #是tensor的形式
print(v.data.numpy()) #先变成tensor，再转换成numpy


tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]


## 注意：pytorch0.4之后的Torch类和Variable类合并，之后的代码按1.4版本写
  
#### 1. Variable可以使用，但返回的是Tensor:

In [11]:
tensor = torch.FloatTensor([[1,2],[3,4]])
v = Variable(tensor)

print(tensor)
print(v) #显示v是tensor 


tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


#### 2. requires_grad是Tensor的属性，默认是False：

In [17]:
a = torch.randn(2,2) 
print("default: ",a.requires_grad)
a.requires_grad_(True) #设置requires_grad属性为true
print("after: ",a.requires_grad)

b=torch.randn(2,2,requires_grad=True) #创建时设置requires_grad属性为true
print("set when created: ",b.requires_grad)

default:  False
after:  True
set when created:  True


#### 3. 用backward()求梯度
注意：
- 每次反向传播，梯度都会**累加**，因此反向传播之前要将梯度清零
- 如果需要backward的tensor是张量，backward函数的参数是与其同型的tensor，tensor的值是每个数对应的权重

In [26]:
a.grad.data.zero_() #梯度清零
b.grad.data.zero_()
c = 2*a + b
print(c.requires_grad) #a和b都是True，因此c为True
tmp = torch.tensor([[1.,1.],[1.,1.]])
c.backward(tmp) #传入和c同型的参数，值是权重
print(a.grad)
print(b.grad)

True
tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
